name: rtdev
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.11
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  location: ^6.0.2
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/db.svg
    - assets/icon/icon.png
    - assets/map/user.png
